add an option to auto-expand model subfolders
Comfy-Org/ComfyUI_frontend pull request #1080
Opened 2024-10-03 18:47 UTC by mcmonkey4eva

for #1006

Very straightforward: just a setting, and if you enable it, when a model root folder is opened, once it loads, call `expandNode` on the folder, and maintain a set to avoid avoid calling expand again after it's happened once

I wouldn't want this on myself, but it's a reasonable enough request so why not

2024-10-03 19:56 UTC, huchenlei requested changes
Can you reserve this recursive expand feature on ctrl + click, which aligns with all other trees?

2024-10-03 22:30 UTC, huchenlei commented
I read https://github.com/Comfy-Org/ComfyUI_frontend/issues/1006 one more pass, and the issue seems to request the auto-expand on search.

2024-10-03 22:31 UTC, huchenlei commented
Closing this PR for now, as it does not implement what the issue is asking for.

2024-10-03 22:31 UTC, closed without merging

2024-10-04 01:19 UTC, mcmonkey4eva commented
ohp you're right my bad