allow dragging embeddings onto text boxes
Comfy-Org/ComfyUI_frontend pull request #1156
Opened 2024-10-07 23:42 UTC by mcmonkey4eva

requested by #1029

hardcoded to 'embeddings' model type only for now (I'm not aware of any third party model types that behave similarly, this is very embeddings-specific)

set to work with any textarea for now (would be somewhere between nontrivial and impossible to only get prompt text inputs, as, well, yknow, there could be any number of nodes used as prompt inputs - primitive, textbox, cliptextencode, any number of third party ones, ...) so if you drag an embedding onto a text box, assume you probably meant to do that.

will preserve selection area, and insert where you have selected, which is pretty neat.

side note: i don't want to talk about how long it took me to figure out the specifics of how to listen to dragging from a tree thing properly. Turned out as usual, random obscure specific framework doesn't do the job any better than the default browser functionality but is basically required regardless. `document.elementFromPoint` is a bit cursed but I don't think pdnd supplies an element anywhere I can find.

`setTimeout` usage looks a bit odd at a glance so I tacked on a comment to explain it

`dropTargetCleanup` naming and usage style copied from GraphCanvas

2024-10-07 23:53 UTC, huchenlei requested changes

2024-10-07 23:53 UTC, huchenlei commented on src/components/sidebar/tabs/ModelLibrarySidebarTab.vue
> +    element: document.body,
Do we really want the drop target to be the whole document? This approach won't give us room if later we want to highlight the dropzone and droppable state.

I would suggest we put this on-hold and redesign the drag and drop system in `app.ts` first.
https://github.com/Comfy-Org/ComfyUI_frontend/blob/2b265141902fa7f0e7804a9e725be78448553152/src/scripts/app.ts#L1015-L1048

Ideally whether a node can accept the drop of an embedding should be defined on that particular node's declaration.

2024-10-10 14:57 UTC, closed without merging

2024-10-10 15:00 UTC, huchenlei commented
Revisit after refactoring of app.ts dnd. We should highlight drop zone and droppable state when dragging. Shipping a feature that is hard to discover/use now is probably not a good idea.

2024-12-22 07:42 UTC, silveroxides commented
@huchenlei has app.ts been refactored by now?

2025-04-27 05:42 UTC, ltdrdata commented
@huchenlei What is the status of this?