Restore backend state when Playwright test finishes
Comfy-Org/ComfyUI_frontend pull request #1168
Opened 2024-10-08 13:24 UTC by christian-byrne

Backup and restore `user` and `models` folders in global setup/teardown of local Playwright tests. 

Backup `user` by making a copy. Backup `models` by renaming and replacing with scaffolding copy (folders only).

Get base ComfyUI path from `DEPLOY_COMFYUI_DIR` var.

2024-10-08 14:31 UTC, huchenlei requested changes
I meet a weild bug that If I cleanup the workflows directory and run `Can show top level saved workflows` test, the generated `workflow1.json` and `workflow2.json` does not get removed. Can you try reproduce that?

Steps:
- Prepare an empty `users/workflows/` directory
- Run `Can show top level saved workflows` under `menu.spec.ts` alone

2024-10-08 14:31 UTC, huchenlei commented on browser_tests/globalSetup.ts
> +      backupPath([process.env.DEPLOY_COMFYUI_DIR, '..', 'user'])
Let's maybe define another env var as the deployment dir might not always be Comfy/web.

2024-10-09 12:28 UTC, christian-byrne commented
> I meet a weild bug that If I cleanup the workflows directory and run `Can show top level saved workflows` test, the generated `workflow1.json` and `workflow2.json` does not get removed. Can you try reproduce that?
> 
> Steps:
> 
> * Prepare an empty `users/workflows/` directory
> * Run `Can show top level saved workflows` under `menu.spec.ts` alone

Having trouble reproducing. I tried with and without `--ui`, running only that test, running only that test file, etc. What command are you starting with?

2024-10-09 12:29 UTC, christian-byrne commented
> I meet a weild bug that If I cleanup the workflows directory and run `Can show top level saved workflows` test, the generated `workflow1.json` and `workflow2.json` does not get removed. Can you try reproduce that?
> 
> Steps:
> 
> * Prepare an empty `users/workflows/` directory
> * Run `Can show top level saved workflows` under `menu.spec.ts` alone

Having trouble reproducing. I tried with and without `--ui`, running only that test, only that test file, etc. What command are you launching with?

2024-10-09 12:38 UTC, christian-byrne commented on browser_tests/globalSetup.ts
> +      backupPath([process.env.DEPLOY_COMFYUI_DIR, '..', 'user'])
Changed to `TEST_COMFYUI_DIR`

2024-10-09 19:05 UTC, huchenlei approved these changes

2024-10-09 19:05 UTC, merged