Show download percentage only if it's over 10%
Comfy-Org/ComfyUI_frontend pull request #1539
Opened 2024-11-14 21:52 UTC by oto-ciulis-tt

2024-11-14 22:08 UTC, huchenlei requested changes
Can you attach more context on why this change is necessary?

2024-11-14 23:30 UTC, oto-ciulis-tt commented
> Can you attach more context on why this change is necessary?

This was requested by @robinjhuang in https://comfy-organization.slack.com/archives/C07H3GLKDPF/p1731551013385499

2024-11-15 00:54 UTC, huchenlei commented
> > Can you attach more context on why this change is necessary?
> 
> This was requested by @robinjhuang in https://comfy-organization.slack.com/archives/C07H3GLKDPF/p1731551013385499

I mean please attach the context in this PR so if we revisit this PR later we know what this PR does and why we decide to do that.

2024-11-16 16:48 UTC, huchenlei approved these changes

2024-11-16 16:48 UTC, merged