add load 3d node support
Comfy-Org/ComfyUI_frontend pull request #1563
Opened 2024-11-16 02:12 UTC by jtydhr88

Hi,
I implemented a node to load local 3d models and output IMAGE for furthur process, such as controlnet, as reference image.
here is a demo video:
https://github.com/user-attachments/assets/703b12ed-9e60-42df-9de2-31fa1df48ce7
Need https://github.com/comfyanonymous/ComfyUI/pull/5564 as BE

2024-11-16 23:41 UTC, huchenlei requested changes

2024-11-16 23:41 UTC, huchenlei commented on src/extensions/core/load3d.ts
> +// @ts-strict-ignore
Please enable ts-strict here.

2024-11-17 02:50 UTC, jtydhr88 commented on src/extensions/core/load3d.ts
> +// @ts-strict-ignore
done

2024-11-17 02:51 UTC, jtydhr88 commented
add stl format support, also add normal and wireframe material support
![image](https://github.com/user-attachments/assets/91f12fde-99be-4531-ace1-01fb0066d96f)

2024-11-17 03:04 UTC, jtydhr88 commented
currently, the two browers tests failed but I am not sure it is caused by my changes, I checked another recent PR, like https://github.com/Comfy-Org/ComfyUI_frontend/pull/1537, it also has such issues @huchenlei

2024-11-17 19:02 UTC, huchenlei commented
> currently, the two browers tests failed but I am not sure it is caused by my changes, I checked another recent PR, like #1537, it also has such issues @huchenlei

Please rebase your branch. The playwright test failure was fixed in https://github.com/Comfy-Org/ComfyUI_frontend/pull/1561

2024-11-17 19:12 UTC, jtydhr88 commented
> > currently, the two browers tests failed but I am not sure it is caused by my changes, I checked another recent PR, like #1537, it also has such issues @huchenlei
> 
> Sorry about that. It was introduced by accident. Please rebase your branch. The playwright test failure was fixed in #1561

Done

2024-11-17 19:37 UTC, huchenlei approved these changes

2024-11-17 19:50 UTC, jtydhr88 commented
/home/runner/work/ComfyUI_frontend/ComfyUI_frontend/src/stores/coreSettings.ts
Error:   5:3  error  'LinkReleaseTriggerMode' is defined but never used  unused-imports/no-unused-imports
One test failed on this line but likely it is caused by another change @huchenlei

2024-11-17 20:13 UTC, merged

2024-12-04 16:09 UTC, yovsac commented
This is exactly what I was looking for for a while! How can I use this node??

2024-12-04 16:22 UTC, jtydhr88 commented
hi @yovsac , as you see, the FE code already merged, 
However, we are still waiting for one PR in core repo https://github.com/comfyanonymous/ComfyUI/pull/5564,
if you real need this feature, you might refer and just "copy" my code in https://github.com/comfyanonymous/ComfyUI/pull/5564 to your local env until the PR merged

2024-12-04 16:46 UTC, yovsac commented
Thank you for your quick reply. Im using Comfyui portable. Can you tell me how I can copy the code?

2024-12-04 21:02 UTC, jtydhr88 commented
@yovsac I just realize coping code to your local env might not a good idea if you are using comfyui portable version, because I am not sure it is already included the FE code here.
However, if you really want to try this, you can follow:
1. create a py file under your ComfyUI\comfy_extras folder, named it nodes_load_3d.py
![image](https://github.com/user-attachments/assets/2109838c-a38a-4020-a8d6-89c0d76db995)

2. copy the code from https://github.com/comfyanonymous/ComfyUI/pull/5564/files into nodes_load_3d.py
3. edit your ComfyUI\nodes.py
![image](https://github.com/user-attachments/assets/cfb8dda7-7b11-4a63-ba7b-5a84dd56be49)
4. go to init_builtin_extra_nodes() method, add one line inside extras_files, 
![image](https://github.com/user-attachments/assets/0c82273f-0a65-4a8e-880c-57693c605a1b)
5. then restart your ComfyUI

Still, this method may not work as your local env might not included the latest FE code.

2024-12-04 21:08 UTC, yovsac commented
Thank you very much. I’ll try that!!

2024-12-04 21:10 UTC, jtydhr88 commented
@yovsac maybe the best idea is, could you help to go the core PR https://github.com/comfyanonymous/ComfyUI/pull/5564, leave your idea and may push it merge quickly?

2024-12-04 21:14 UTC, yovsac commented
I left a message. Hope they hurry up!