[Electron] Allow users to submit error reports
Comfy-Org/ComfyUI_frontend pull request #1633
Opened 2024-11-21 19:34 UTC by pythongosssss

Adds a Send Report button to the execution error dialog to allow users to report errors.  
![image](https://github.com/user-attachments/assets/54e1f968-c304-4b99-a6d6-836944fb8c82)

This submits the error message, stacktrace and node type.
We can extend this in future to allow opting in to include more details if they are found to be useful for diagnosing issues (e.g. logs, installed nodes, version, etc)

2024-11-21 19:56 UTC, huchenlei commented on src/components/dialog/content/error/ReportIssueButton.vue
> +const emit = defineEmits<{
nit: Unused emit.

2024-11-21 19:56 UTC, huchenlei commented on src/components/dialog/content/error/ReportIssueButton.vue
> +    severity="secondary"
nit: Can we change severity to success when successfully submitted?

2024-11-21 19:56 UTC, huchenlei commented on src/components/dialog/content/error/ReportIssueButton.vue
> +  <Button
We probably need a mechanism to tell user who they are sending to? A tooltip might be helpful here. For example: `Report the error to Comfy-Org`.

2024-11-21 19:56 UTC, huchenlei commented on src/components/dialog/content/error/ReportIssueButton.vue
> +    await electronAPI().sendErrorToSentry(error.exception_message, {
@robinjhuang PTAL. I am not very sure if this is the correct format we are expecting in the Sentry setup.

2024-11-21 20:19 UTC, huchenlei approved these changes

2024-11-22 00:59 UTC, huchenlei commented on src/components/dialog/content/error/ReportIssueButton.vue
> +    await electronAPI().sendErrorToSentry(error.exception_message, {
Slack chat from @robinjhuang 
>  Can we send the logs and system info in the report as well? Everything except the workflow for now would be good i think

2024-11-22 01:36 UTC, robinjhuang requested changes
Can we send the entire report except workflow? Having the logs and system info would be helpful.

2024-11-22 22:04 UTC, huchenlei commented
Offline discussion: we go with basic stacktrace now, and potentially strip out the user base directory that might potentially contain user name. (Happen in electron side)

2024-11-22 22:04 UTC, merged