forward mouse events from textareas to canvas
Comfy-Org/ComfyUI_frontend pull request #1911
Opened 2024-12-14 19:34 UTC by fahdarafat

This should fix [1773](https://github.com/Comfy-Org/ComfyUI_frontend/issues/1773).
I'm not sure though if there are more DOM elements to handle. This currently only handles textareas

https://github.com/user-attachments/assets/3811eddd-9d01-4c8c-a918-a801e6d0db01

2024-12-14 19:59 UTC, huchenlei commented
@webfiltered Can you take a look at this PR?

2024-12-15 16:07 UTC, webfiltered requested changes
Awesome, thank you!  I had this on my to-do list, so it's much appreciated!

(this review looks like a lot of changes, but really it's just three very minor ones)

2024-12-15 16:07 UTC, webfiltered commented on src/scripts/widgets.ts
> +  inputEl.addEventListener('mousedown', (event: PointerEvent) => {
```suggestion
  inputEl.addEventListener('pointerdown', (event: PointerEvent) => {
```

Need to use `pointer` events for this - `mouse` lacks some required features.

2024-12-15 16:07 UTC, webfiltered commented on src/scripts/widgets.ts
> +  inputEl.addEventListener('mousemove', (event: PointerEvent) => {
```suggestion
  inputEl.addEventListener('pointermove', (event: PointerEvent) => {
```

2024-12-15 16:07 UTC, webfiltered commented on src/scripts/widgets.ts
> +  inputEl.addEventListener('mouseup', (event: PointerEvent) => {
```suggestion
  inputEl.addEventListener('pointerup', (event: PointerEvent) => {
```

2024-12-15 16:07 UTC, webfiltered commented on src/scripts/widgets.ts
> +      event.preventDefault()
```suggestion
```

It's alright to let this hit both the DOM element and canvas in this instance.  Otherwise there's no way for anyone to get a middle click on their dom widget.

2024-12-15 16:07 UTC, webfiltered commented on src/scripts/widgets.ts
> +      app.canvas.pointer.onDragStart(app.canvas.pointer)
```suggestion
```

Now that we're using `pointer` instead of `mouse`, we can remove the workaround - creative, though!

2024-12-15 16:07 UTC, webfiltered commented on src/scripts/widgets.ts
> +    if (event.buttons === 4) {
```suggestion
    if ((event.buttons & 4) === 4) {
```

`buttons` is a binary flag value (or "register" if you're familiar with hardware stuff) - this way it will match even if you are holding middle button and another button.

2024-12-15 16:14 UTC, webfiltered approved these changes

2024-12-15 20:50 UTC, huchenlei approved these changes

2024-12-15 20:50 UTC, merged