Fix workflow-insert with reroute nodes
Comfy-Org/ComfyUI_frontend pull request #2008
Opened 2024-12-22 07:04 UTC by christian-byrne

2024-12-22 14:55 UTC, webfiltered approved these changes
With tests, even!  Thank you.  😄

2024-12-22 21:15 UTC, huchenlei requested changes
Can we collapse the sidebar before taking the screenshot?

Also I would like a more minimal reproduction for the example workflow used for this test to be more isolated to other features.

2024-12-22 23:58 UTC, christian-byrne commented
> b6463b5

2024-12-23 00:51 UTC, huchenlei approved these changes

2024-12-23 00:51 UTC, merged