Allow comfyui to use images as background
Comfy-Org/ComfyUI_frontend pull request #591
Opened 2024-08-22 10:31 UTC by mijuku233

### **This change allows users to use images as backgrounds by modifying the color palette configuration file.**

### How to use an image as a background:

Export a palette profile and edit it.

Set the value of `"bg-img"` to `url('your image path/background image.png')`. 

> Example:`"bg-img": "#202020"` ➡ `"bg-img": "url('Users/Mijuku/Pictures/bg.png')"`.

In addition, setting the value of `CLEAR_BACKGROUND_COLOR` to `transparent` can prevent the background from disappearing due to scaling the canvas.

Finally, import the modified configuration file in the comfyui palette and refresh the browser

_If you think it is troublesome to modify the palette configuration file, I have the modified configuration file here. 
[ImgBG.json](https://github.com/user-attachments/files/16709173/ImgBG.json)
Just import the ImgBG.json configuration file in the comfyui palette, then rename the background image to bg.png and place it in the comfyui/web directory, and refresh the browser to take effect._

2024-08-22 13:41 UTC, huchenlei requested changes
The method of using `bg-img` to replace `background-color` seems a bit off to me. Can you make that `bg-img` an optional field in `colorPalette.ts`? Also the schema in `types/colorPalette.ts` needs an update to reflect the changes here.

2024-08-23 05:53 UTC, mijuku233 commented
> The method of using `bg-img` to replace `background-color` seems a bit off to me. Can you make that `bg-img` an optional field in `colorPalette.ts`? Also the schema in `types/colorPalette.ts` needs an update to reflect the changes here.

Modified, `bg-img` is set as an optional field.

My coding skills are very limited, if there is anything wrong, please modify it directly.

2024-08-28 12:02 UTC, bjszd commented on src/assets/css/style.css
> +  background: var(--bg-img) no-repeat center /cover;
With your change the background color is gone for users without an image. But it is possible to keep the background color and the image. That way the color will be shown while the image is loading for those users that set a background image. And for the rest the color will still be there.

```suggestion
  background: var(--bg-color) var(--bg-img) no-repeat center /cover;
```

2024-08-28 12:03 UTC, bjszd commented on src/assets/css/style.css
> +  background: var(--bg-img) no-repeat center /cover;
If you make the above change then you won't need to specify hex values in the `bg-img` property, only set it when there's an image url.

2024-08-28 20:53 UTC, mcmonkey4eva commented on src/assets/css/style.css
> +  background: var(--bg-img) no-repeat center /cover;
better yet: just do `background: var(--bg-color);`, at which point you can just set `bg-color: "url('Users/Mijuku/Pictures/bg.png') no-repeat center /cover";` and get the intended result without altering anything else?

2024-08-28 21:03 UTC, huchenlei commented
> better yet: just do background: var(--bg-color);, at which point you can just set bg-color: "url('Users/Mijuku/Pictures/bg.png') no-repeat center /cover"; and get the intended result without altering anything else?

I think custom background is already achievable with current setup. Closing this for now.

2024-08-30 03:25 UTC, mijuku233 commented on src/assets/css/style.css
> +  background: var(--bg-img) no-repeat center /cover;
> better yet: just do `background: var(--bg-color);`, at which point you can just set `bg-color: "url('Users/Mijuku/Pictures/bg.png') no-repeat center /cover";` and get the intended result without altering anything else?

If you only set `var(--bg-color)`, other settings that use `var(--bg-color)` will also be affected.

Setting `background: var(--bg-img)` alone can avoid this problem.

![屏幕截图 2024-08-30 111719](https://github.com/user-attachments/assets/e8c3b25d-cdef-4fd9-ad55-c52228c82db0)

![屏幕截图 2024-08-30 111818](https://github.com/user-attachments/assets/a18d8ada-eee0-49b2-af95-0ed2fcf164e9)

2024-08-30 04:42 UTC, mijuku233 commented
> > better yet: just do background: var(--bg-color);, at which point you can just set bg-color: "url('Users/Mijuku/Pictures/bg.png') no-repeat center /cover"; and get the intended result without altering anything else?
> 
> I think custom background is already achievable with current setup. Closing this for now.

To customize the image background, at least change `background-color` to `background`.
But there will be a problem if you customize the background by setting `var(--bg-color)`, as I showed above.
Setting the variable `bg-img` separately can avoid that problem. Here is the modified and more concise code:

https://github.com/Comfy-Org/ComfyUI_frontend/compare/main...mijuku233:ComfyUI_frontend:IMG_BG

![image](https://github.com/user-attachments/assets/aac5e8ab-3844-405b-b2a1-893942082a49)

2024-09-01 09:44 UTC, mijuku233 commented
Submitted new PR:#698

2024-09-01 09:44 UTC, closed without merging