(PR) proper icon management
Comfy-Org/ComfyUI_frontend pull request #757
Opened 2024-09-08 03:27 UTC by dmx974

2024-09-09 01:29 UTC, huchenlei commented
> Mandatory changes to prepare the front stack for the upcoming updates and improvements (i.e. tabs, routing, autoimport icons, tailwind ...)

The failing playwright test is caused by tailwind altering the appearance of the legacy menu. See following picture for reference. 

Idealy we don't want to affect people who use the legacy menu.
![image](https://github.com/user-attachments/assets/73018701-6bc3-4985-ad65-72b78ffc4bcc)

2024-09-09 06:00 UTC, huchenlei requested changes
I would like to see the PR breaking down into a few smaller ones:

- Format index.html / vite.config.mts
- Add router
- Add iconify
- Fix tailwindcss

2024-09-09 06:00 UTC, huchenlei commented on src/main.ts
> +import '@/assets/css/user.css'
Please revert the change to `user.css` as it is for users to modify in the final build target to add extra rules. Importing `user.css` here would cause `user.css` not appear in the final build target.

2024-09-09 07:52 UTC, huchenlei commented
TailwindCSS setup is done in #768. You can now safely proceed with rest of the PRs with tailwind classes.

2024-09-09 17:00 UTC, dmx974 commented on src/main.ts
> +import '@/assets/css/user.css'
Copy that!

2024-09-10 23:53 UTC, huchenlei approved these changes
LGTM

2024-09-10 23:53 UTC, merged

2024-09-22 11:21 UTC, mcmonkey4eva commented
This PR hardcoded the frontend to only work as a webroot, ie owner of the `/` route, which is not necessarily true for all deployments, and in fact actively is not in many cases. SwarmUI for example does not deploy comfy at the webroot, and there are many users with special apache2/nginx configured subroutes and similar.