Fix routing
Comfy-Org/ComfyUI_frontend pull request #939
Opened 2024-09-23 10:23 UTC by mcmonkey4eva

This reverts bad changes to routing handling and readds code that was working before.

Opened as a draft as it's still regressed from where it was at the time of my previous fix PR and I need to figure out what happened still

2024-09-23 23:44 UTC, huchenlei commented on vite.config.mts
> +      '/object_info': {
Why do we need to delegate /object_info?

2024-09-23 23:53 UTC, huchenlei requested changes
https://github.com/Comfy-Org/ComfyUI_frontend/issues/941 is filed against 1.2.49 while we are reverting changes on dev1.3 to fix it. I don't see the connection here.

2024-09-24 04:54 UTC, mcmonkey4eva commented
The bug was introduced in 1.2.49, fixed by https://github.com/Comfy-Org/ComfyUI_frontend/pull/927 broken again by https://github.com/Comfy-Org/ComfyUI_frontend/pull/936 and broken worse by https://github.com/Comfy-Org/ComfyUI_frontend/pull/929 and https://github.com/Comfy-Org/ComfyUI_frontend/pull/931

This is a critical breaking core bug in deployed public ComfyUI copy of the frontend

You previously told me to target PRs against dev1.3, so I've been doing so, and this one has to target dev1.3 to avoid becoming a merge conflict if targeted at main due to invalid/breaking PRs being merged onto dev1.3

2024-09-24 06:01 UTC, huchenlei approved these changes

2024-09-24 06:01 UTC, merged