Reset FileInput value after load
Comfy-Org/ComfyUI_frontend pull request #958
Opened 2024-09-24 07:38 UTC by AustinMroz

When a file is browsed for, the fileInput remains associated with the chosen file even after the associated workflow is loaded. If a user attempts to load the same file again, the onchange event does not fire and loading fails silently. This is fixed by clearing the fileInput after the workflow has been loaded.

Out of an abundance of caution, the onchange is made async to ensure the fileInput isn't cleared until after the workflow has loaded.

This is a long standing issue which had befuddled me for many months.

2024-09-24 07:49 UTC, huchenlei commented on src/scripts/ui.ts
> +      onchange: async () => {
Can you add a playwright testcase for this change? See https://github.com/Comfy-Org/ComfyUI_frontend/tree/main/browser_tests

2024-09-24 07:50 UTC, huchenlei commented on src/scripts/ui.ts
> +      onchange: async () => {
You can use https://github.com/Comfy-Org/ComfyUI_frontend/blob/2387a5e9bdb5fc30047c765b2788fecec465c318/browser_tests/ComfyPage.ts#L326-L331 for file upload.

2024-09-24 23:43 UTC, huchenlei requested changes
Please put the setting changes in before/after tests for proper setup/teardown, as if the test expectation fails, the setting side-effect can cause other tests to fail.

2024-09-25 00:03 UTC, AustinMroz commented
Is there a way to have the before and after functions to apply to just this test and not the `Can load workflow with string node id` test other than creating a new test group?

2024-09-25 02:42 UTC, huchenlei commented
> Is there a way to have the before and after functions to apply to just this test and not the `Can load workflow with string node id` test other than creating a new test group?

I think the current way is to have a new describe group to hold the extra setup/teardown logic.

2024-09-25 06:25 UTC, huchenlei approved these changes

2024-09-25 06:25 UTC, merged