allow custom bypass color
Comfy-Org/ComfyUI_frontend pull request #993
Opened 2024-09-26 08:53 UTC by mcmonkey4eva

NOTE: see my comment here https://github.com/Comfy-Org/ComfyUI_frontend/issues/964 regardless the design of the theme/color palette system (the current impl feels very hacky, and it's made worse by trying to add a color that isn't explicitly an upstreamed value in litegraph or css, as is the case here).

Regardless, this PR does let you change the color of node bypass if you want, for example here I made it green (`#00FF00`)
![image](https://github.com/user-attachments/assets/09416755-e0fc-4205-b5b9-fd304a4eff17)

2024-09-26 23:25 UTC, huchenlei requested changes
The node color configuration should be in `litegraph_base` category.

2024-10-02 13:53 UTC, mcmonkey4eva commented
it's not valid to be there (as that's, for, yknow, litegraph) but it doesn't break anything, so sure why not - moved

2024-10-02 14:49 UTC, huchenlei approved these changes

2024-10-02 14:49 UTC, merged

2024-10-02 21:38 UTC, JorgeR81 commented
Where are the settings for this ? ( I don't see it in v1.3.6 )

Do we have to create a custom color palette ?
Is there a guide to do this ?

2024-10-03 10:24 UTC, mcmonkey4eva commented
Yes, create a custom color palette
At the top of settings, there's Color Palette, just select your preference and click "Export"
![image](https://github.com/user-attachments/assets/32963edc-e1ae-4b87-95f7-f0429dfd277f)

that'll give you a json file. Open it up in a text editor, find node bypass color
![image](https://github.com/user-attachments/assets/d849bc08-bf72-4720-a265-b524688e9eb1)
and edit it to a hex color you like, eg `#00FF00` for glowing neon green lol

Also at the top change the name:
![image](https://github.com/user-attachments/assets/b1cc71a4-bdeb-45d9-afc7-3b21697f32d6)

Then back in the settings menu click "Import" and select your file
![image](https://github.com/user-attachments/assets/0ea16509-462b-4c98-b98d-bfed87668ec6)

Then go bypass something
![image](https://github.com/user-attachments/assets/8a716c8e-8230-4b87-b4b8-847df606b197)

2024-10-03 16:13 UTC, JorgeR81 commented
It's working fine. Thanks !

But I can only use 1 custom palette at a time.

When I import a new one, the previous one is gone.

Is this a known issue ?